/**
 * @file lib/abuseMonitor.ts
 * @description Records and retrieves API usage events for admin monitoring.
 *
 * Every call to /api/recommend is logged (allowed and blocked) with enough
 * context to identify abuse patterns without storing personal data.
 *
 * PRIVACY NOTE:
 * We store partial IPs only (first 3 octets of IPv4, e.g. "192.168.1.*")
 * to provide abuse detection while reducing PII exposure. Full IPs are
 * never written to the abuse log.
 *
 * KV KEY SCHEMA:
 *   "apilog:{unix-ms}"     — individual event, 7-day TTL
 *   "apilog:index"         — list of up to 200 keys, newest-first (lpush/ltrim)
 *   "security:suspicious:{unix-ms}" — written by lib/sanitize.ts, read here
 */

export interface ApiLogEntry {
  /** ISO-8601 timestamp of the request */
  timestamp: string;
  /** First 3 octets of the client IP e.g. "192.168.1.*" */
  partialIp: string;
  /** Whether the request was served or rejected */
  allowed: boolean;
  /** Only set when allowed === false */
  blockedReason?: "rate_limit" | "hard_ceiling" | "unauthorized" | "validation_failed";
  /** Filament material from the request (allowed requests only) */
  filamentType?: string;
  /** Print quality tier — maps to inputs.printPriority (allowed requests only) */
  qualityTier?: string;
  /** Wall-clock time the request took to complete in ms (allowed requests only) */
  durationMs?: number;
  /** True when request used owner bypass token — shows owner access is active */
  isOwner?: boolean;
  /** Input tokens consumed by Claude API call (allowed requests only) */
  inputTokens?: number;
  /** Output tokens generated by Claude API call (allowed requests only) */
  outputTokens?: number;
  /** Calculated cost in USD (6 decimal precision) (allowed requests only) */
  costUsd?: number;
  /** Claude model used (e.g., "claude-3-5-haiku", "claude-3-5-sonnet", "claude-3-opus") */
  model?: string;
}

// ── IP masking ────────────────────────────────────────────────────────────────

/**
 * Masks an IP address to the first 3 octets for privacy-preserving logging.
 *
 * Examples:
 *   "192.168.1.100"  → "192.168.1.*"
 *   "2001:db8::1"    → "2001:db8:0:0:*"
 *   "unknown"        → "unknown"
 */
export function maskIp(ip: string): string {
  if (!ip || ip === "unknown") return "unknown";

  if (ip.includes(":")) {
    // IPv6 — keep the first 4 groups
    return ip.split(":").slice(0, 4).join(":") + ":*";
  }

  // IPv4 — mask the last octet
  const parts = ip.split(".");
  if (parts.length === 4) return `${parts[0]}.${parts[1]}.${parts[2]}.*`;
  return ip;
}

// ── Cost calculation ──────────────────────────────────────────────────────────

/**
 * Pricing constants per million tokens (as of April 2026).
 * Source: https://www.anthropic.com/pricing/claude
 */
const MODEL_PRICING = {
  // Claude 3.5 Haiku — fastest, most affordable
  "claude-3-5-haiku": { inputPerMillion: 0.80, outputPerMillion: 4.00 },
  // Claude 3.5 Sonnet — balanced
  "claude-3-5-sonnet": { inputPerMillion: 3.00, outputPerMillion: 15.00 },
  // Claude 3 Opus — most capable
  "claude-3-opus": { inputPerMillion: 15.00, outputPerMillion: 75.00 },
} as const;

/**
 * Calculates the cost in USD for an API call based on tokens consumed.
 *
 * @param model — Claude model identifier (e.g., "claude-3-5-sonnet-20241022")
 * @param inputTokens — Number of input tokens
 * @param outputTokens — Number of output tokens
 * @returns Cost in USD (6 decimal precision)
 *
 * Examples:
 *   calculateCost("claude-3-5-sonnet", 1000, 500)
 *     = (1000 * 3.00 / 1_000_000) + (500 * 15.00 / 1_000_000)
 *     = 0.000003 + 0.0000075 = 0.0000105 ≈ $0.00001
 */
export function calculateCost(
  model: string,
  inputTokens: number,
  outputTokens: number,
): number {
  // Extract base model name (e.g., "claude-3-5-sonnet" from "claude-3-5-sonnet-20241022")
  const baseModel = model.split("-").slice(0, 3).join("-") as keyof typeof MODEL_PRICING;

  const pricing = MODEL_PRICING[baseModel];
  if (!pricing) {
    console.warn(`[calculateCost] Unknown model: ${model}, defaulting to Haiku pricing`);
    return (
      (inputTokens * MODEL_PRICING["claude-3-5-haiku"].inputPerMillion) / 1_000_000 +
      (outputTokens * MODEL_PRICING["claude-3-5-haiku"].outputPerMillion) / 1_000_000
    );
  }

  const cost =
    (inputTokens * pricing.inputPerMillion) / 1_000_000 +
    (outputTokens * pricing.outputPerMillion) / 1_000_000;

  // Return with 6 decimal precision
  return Math.round(cost * 1_000_000) / 1_000_000;
}

// ── Write ─────────────────────────────────────────────────────────────────────

/**
 * Records an API call event to Vercel KV.
 *
 * Designed as fire-and-forget — the caller should use `void logApiCall(...)`.
 * Never throws; logging failure must not disrupt the user request.
 */
export async function logApiCall(entry: ApiLogEntry): Promise<void> {
  try {
    const { kv } = await import("@vercel/kv");
    const key = `apilog:${Date.now()}`;

    // Store the event with a 7-day TTL
    await kv.set(key, entry, { ex: 7 * 86_400 });

    // Prepend to the index and cap it at 200 entries
    await kv.lpush("apilog:index", key);
    await kv.ltrim("apilog:index", 0, 199);
  } catch (err) {
    if (process.env.NODE_ENV === "development") {
      console.warn("[abuseMonitor] Log write failed:", err);
    }
    // Silently swallow in production — monitoring must never break the API
  }
}

// ── Read ──────────────────────────────────────────────────────────────────────

/**
 * Retrieves the most recent API log entries for admin display.
 *
 * @param limit - Maximum number of entries to return (default 50)
 * @returns Array of log entries, most recent first. Empty array on any error.
 */
export async function getRecentApiLogs(limit = 50): Promise<ApiLogEntry[]> {
  try {
    const { kv } = await import("@vercel/kv");

    const keys = await kv.lrange("apilog:index", 0, limit - 1);
    if (!keys || keys.length === 0) return [];

    const entries = await Promise.all(
      (keys as string[]).map((k) => kv.get<ApiLogEntry>(k)),
    );
    return entries.filter((e): e is ApiLogEntry => e !== null);
  } catch {
    return [];
  }
}

// ── Statistics type ──────────────────────────────────────────────────────────

export interface ApiStats {
  totalToday: number;
  allowedToday: number;
  blockedToday: number;
  suspiciousToday: number;
  topFilamentTypes: Array<{ type: string; count: number }>;
  costMetrics: {
    today: number;
    week: number;
    month: number;
    year: number;
    byModel: Record<string, number>;
  };
  tokenMetrics: {
    totalInputToday: number;
    totalOutputToday: number;
    avgTokensPerRequestToday: number;
  };
}

/**
 * Computes summary statistics from the last 200 log entries.
 * All counts and costs are scoped to time periods (today, this week, this month, this year).
 */
export async function getApiStats(): Promise<ApiStats> {
  const EMPTY = {
    totalToday: 0,
    allowedToday: 0,
    blockedToday: 0,
    suspiciousToday: 0,
    topFilamentTypes: [] as Array<{ type: string; count: number }>,
    costMetrics: {
      today: 0,
      week: 0,
      month: 0,
      year: 0,
      byModel: {} as Record<string, number>,
    },
    tokenMetrics: {
      totalInputToday: 0,
      totalOutputToday: 0,
      avgTokensPerRequestToday: 0,
    },
  };

  try {
    const logs = await getRecentApiLogs(200);
    const now = new Date();
    const today = now.toISOString().slice(0, 10); // "YYYY-MM-DD"

    // Calculate time boundaries
    const oneDayAgo = new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000);
    const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    const oneYearAgo = new Date(now.getTime() - 365 * 24 * 60 * 60 * 1000);

    const todayLogs = logs.filter((l) => l.timestamp.startsWith(today));
    const weekLogs = logs.filter((l) => new Date(l.timestamp) >= sevenDaysAgo);
    const monthLogs = logs.filter((l) => new Date(l.timestamp) >= thirtyDaysAgo);
    const yearLogs = logs.filter((l) => new Date(l.timestamp) >= oneYearAgo);

    // Tally filament types across allowed requests today
    const filamentCounts: Record<string, number> = {};
    for (const l of todayLogs) {
      if (l.allowed && l.filamentType) {
        filamentCounts[l.filamentType] = (filamentCounts[l.filamentType] ?? 0) + 1;
      }
    }
    const topFilamentTypes = Object.entries(filamentCounts)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([type, count]) => ({ type, count }));

    // Calculate costs and tokens for different time periods
    const calculateCostsForLogs = (logsSubset: ApiLogEntry[]) => {
      let totalCost = 0;
      let totalInput = 0;
      let totalOutput = 0;
      const costByModel: Record<string, number> = {};

      for (const l of logsSubset) {
        if (l.allowed && l.costUsd) {
          totalCost += l.costUsd;
        }
        if (l.allowed && l.inputTokens) {
          totalInput += l.inputTokens;
        }
        if (l.allowed && l.outputTokens) {
          totalOutput += l.outputTokens;
        }
        if (l.allowed && l.model && l.costUsd) {
          costByModel[l.model] = (costByModel[l.model] ?? 0) + l.costUsd;
        }
      }

      return { totalCost, totalInput, totalOutput, costByModel };
    };

    const todayMetrics = calculateCostsForLogs(todayLogs);
    const weekMetrics = calculateCostsForLogs(weekLogs);
    const monthMetrics = calculateCostsForLogs(monthLogs);
    const yearMetrics = calculateCostsForLogs(yearLogs);

    // Calculate average tokens per request today
    const allowedTodayWithTokens = todayLogs.filter(
      (l) => l.allowed && l.inputTokens && l.outputTokens,
    );
    const avgTokensPerRequestToday =
      allowedTodayWithTokens.length > 0
        ? Math.round(
            (todayMetrics.totalInput + todayMetrics.totalOutput) /
              allowedTodayWithTokens.length,
          )
        : 0;

    // Count today's security events from KV (written by lib/sanitize.ts)
    let suspiciousToday = 0;
    try {
      const { kv } = await import("@vercel/kv");
      const [, secKeys] = await kv.scan(0, {
        match: "security:suspicious:*",
        count: 500,
      }) as unknown as [number, string[]];

      suspiciousToday = (secKeys ?? []).filter((k) => {
        const tsMs = parseInt(k.split(":")[2] ?? "0", 10);
        return tsMs > 0 && new Date(tsMs).toISOString().startsWith(today);
      }).length;
    } catch {
      // Security event count is best-effort
    }

    return {
      totalToday: todayLogs.length,
      allowedToday: todayLogs.filter((l) => l.allowed).length,
      blockedToday: todayLogs.filter((l) => !l.allowed).length,
      suspiciousToday,
      topFilamentTypes,
      costMetrics: {
        today: Math.round(todayMetrics.totalCost * 100) / 100,
        week: Math.round(weekMetrics.totalCost * 100) / 100,
        month: Math.round(monthMetrics.totalCost * 100) / 100,
        year: Math.round(yearMetrics.totalCost * 100) / 100,
        byModel: todayMetrics.costByModel,
      },
      tokenMetrics: {
        totalInputToday: todayMetrics.totalInput,
        totalOutputToday: todayMetrics.totalOutput,
        avgTokensPerRequestToday,
      },
    };
  } catch {
    return EMPTY;
  }
}
