import { createHash } from "crypto";
import type {
  EquipmentPrinter,
  EquipmentSurface,
  EquipmentNozzle,
} from "./equipmentSchemas";

/**
 * ─── Default Equipment Data ────────────────────────────────────────────────────
 * Hardcoded equipment lists extracted from InputForm.tsx.
 * These are used as fallback when KV is unavailable and as seed data on first
 * initialization.
 *
 * UUIDs are deterministically generated from the content (name + group) so they're
 * consistent across runs.
 */

/**
 * Generate a deterministic UUID v4-like string based on input.
 * Not a true UUID v4, but valid UUID format for our purposes.
 */
function generateDeterministicUuid(input: string): string {
  const hash = createHash("sha256").update(input).digest("hex");
  // Format as UUID: 8-4-4-4-12
  const uuid = `${hash.substring(0, 8)}-${hash.substring(8, 12)}-4${hash.substring(
    13,
    16
  )}-a${hash.substring(17, 20)}-${hash.substring(20, 32)}`;
  return uuid;
}

// ─── Default Printers ──────────────────────────────────────────────────────────

export const DEFAULT_PRINTERS: EquipmentPrinter[] = [
  // Bambu Lab
  {
    id: generateDeterministicUuid("Bambu Lab A1 Mini|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "A1 Mini",
    group: "Bambu Lab",
    maxBedTempC: 65,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab A1 Mini Combo|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "A1 Mini Combo",
    group: "Bambu Lab",
    maxBedTempC: 65,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab A1|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "A1",
    group: "Bambu Lab",
    maxBedTempC: 65,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 384,
    buildPlateY: 384,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab A1 Combo|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "A1 Combo",
    group: "Bambu Lab",
    maxBedTempC: 65,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 384,
    buildPlateY: 384,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab P1P|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "P1P",
    group: "Bambu Lab",
    maxBedTempC: 110,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab P1S|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "P1S",
    group: "Bambu Lab",
    maxBedTempC: 110,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab P2S|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "P2S",
    group: "Bambu Lab",
    maxBedTempC: 110,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab X1 Carbon|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "X1 Carbon",
    group: "Bambu Lab",
    maxBedTempC: 110,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab X1E|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "X1E",
    group: "Bambu Lab",
    maxBedTempC: 110,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Lab H2D|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "H2D",
    group: "Bambu Lab",
    maxBedTempC: 110,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },

  // Creality
  {
    id: generateDeterministicUuid("Creality Ender 3|Creality"),
    vendorName: "Creality",
    modelName: "Ender 3",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 240,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Ender 3 V2|Creality"),
    vendorName: "Creality",
    modelName: "Ender 3 V2",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 240,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Ender 3 S1|Creality"),
    vendorName: "Creality",
    modelName: "Ender 3 S1",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 250,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Ender 3 S1 Pro|Creality"),
    vendorName: "Creality",
    modelName: "Ender 3 S1 Pro",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Ender 3 V3|Creality"),
    vendorName: "Creality",
    modelName: "Ender 3 V3",
    group: "Creality",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Ender 3 V3 SE|Creality"),
    vendorName: "Creality",
    modelName: "Ender 3 V3 SE",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Ender 3 V3 KE|Creality"),
    vendorName: "Creality",
    modelName: "Ender 3 V3 KE",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Ender 5 S1|Creality"),
    vendorName: "Creality",
    modelName: "Ender 5 S1",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Ender 5 Plus|Creality"),
    vendorName: "Creality",
    modelName: "Ender 5 Plus",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 240,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 350,
    buildPlateY: 350,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality K1|Creality"),
    vendorName: "Creality",
    modelName: "K1",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 300,
    buildPlateY: 300,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality K1 Max|Creality"),
    vendorName: "Creality",
    modelName: "K1 Max",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 300,
    buildPlateY: 300,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality K1C|Creality"),
    vendorName: "Creality",
    modelName: "K1C",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 300,
    buildPlateY: 300,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality K2 Plus|Creality"),
    vendorName: "Creality",
    modelName: "K2 Plus",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 300,
    buildPlateY: 300,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality CR-10 Smart Pro|Creality"),
    vendorName: "Creality",
    modelName: "CR-10 Smart Pro",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 240,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 300,
    buildPlateY: 300,
    active: true,
  },
  {
    id: generateDeterministicUuid("Creality Sermoon V2|Creality"),
    vendorName: "Creality",
    modelName: "Sermoon V2",
    group: "Creality",
    maxBedTempC: 100,
    maxNozzleTempC: 240,
    isEnclosed: true,
    isDirectDrive: false,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },

  // Prusa
  {
    id: generateDeterministicUuid("Prusa i3 MK3S+|Prusa"),
    vendorName: "Prusa",
    modelName: "i3 MK3S+",
    group: "Prusa",
    maxBedTempC: 100,
    maxNozzleTempC: 280,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 250,
    buildPlateY: 210,
    active: true,
  },
  {
    id: generateDeterministicUuid("Prusa MK4|Prusa"),
    vendorName: "Prusa",
    modelName: "MK4",
    group: "Prusa",
    maxBedTempC: 120,
    maxNozzleTempC: 300,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 250,
    buildPlateY: 210,
    active: true,
  },
  {
    id: generateDeterministicUuid("Prusa MK4S|Prusa"),
    vendorName: "Prusa",
    modelName: "MK4S",
    group: "Prusa",
    maxBedTempC: 120,
    maxNozzleTempC: 300,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 250,
    buildPlateY: 210,
    active: true,
  },
  {
    id: generateDeterministicUuid("Prusa MINI+|Prusa"),
    vendorName: "Prusa",
    modelName: "MINI+",
    group: "Prusa",
    maxBedTempC: 100,
    maxNozzleTempC: 280,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 180,
    buildPlateY: 180,
    active: true,
  },
  {
    id: generateDeterministicUuid("Prusa XL|Prusa"),
    vendorName: "Prusa",
    modelName: "XL",
    group: "Prusa",
    maxBedTempC: 120,
    maxNozzleTempC: 300,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 360,
    buildPlateY: 360,
    active: true,
  },
  {
    id: generateDeterministicUuid("Prusa Core One|Prusa"),
    vendorName: "Prusa",
    modelName: "Core One",
    group: "Prusa",
    maxBedTempC: 120,
    maxNozzleTempC: 300,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 210,
    buildPlateY: 250,
    active: true,
  },

  // Elegoo
  {
    id: generateDeterministicUuid("Elegoo Neptune 3 Pro|Elegoo"),
    vendorName: "Elegoo",
    modelName: "Neptune 3 Pro",
    group: "Elegoo",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Elegoo Neptune 4|Elegoo"),
    vendorName: "Elegoo",
    modelName: "Neptune 4",
    group: "Elegoo",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 225,
    buildPlateY: 225,
    active: true,
  },
  {
    id: generateDeterministicUuid("Elegoo Neptune 4 Pro|Elegoo"),
    vendorName: "Elegoo",
    modelName: "Neptune 4 Pro",
    group: "Elegoo",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 225,
    buildPlateY: 225,
    active: true,
  },
  {
    id: generateDeterministicUuid("Elegoo Neptune 4 Plus|Elegoo"),
    vendorName: "Elegoo",
    modelName: "Neptune 4 Plus",
    group: "Elegoo",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 225,
    buildPlateY: 225,
    active: true,
  },
  {
    id: generateDeterministicUuid("Elegoo Neptune 4 Max|Elegoo"),
    vendorName: "Elegoo",
    modelName: "Neptune 4 Max",
    group: "Elegoo",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },
  {
    id: generateDeterministicUuid("Elegoo Neptune 4 X|Elegoo"),
    vendorName: "Elegoo",
    modelName: "Neptune 4 X",
    group: "Elegoo",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 225,
    buildPlateY: 225,
    active: true,
  },

  // Flashforge
  {
    id: generateDeterministicUuid("Flashforge Adventurer 5M|Flashforge"),
    vendorName: "Flashforge",
    modelName: "Adventurer 5M",
    group: "Flashforge",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 165,
    buildPlateY: 165,
    active: true,
  },
  {
    id: generateDeterministicUuid("Flashforge Adventurer 5M Pro|Flashforge"),
    vendorName: "Flashforge",
    modelName: "Adventurer 5M Pro",
    group: "Flashforge",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 165,
    buildPlateY: 165,
    active: true,
  },
  {
    id: generateDeterministicUuid("Flashforge Creator 4|Flashforge"),
    vendorName: "Flashforge",
    modelName: "Creator 4",
    group: "Flashforge",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: false,
    isDirectDrive: false,
    buildPlateX: 200,
    buildPlateY: 200,
    active: true,
  },
  {
    id: generateDeterministicUuid("Flashforge Guider 3 Ultra|Flashforge"),
    vendorName: "Flashforge",
    modelName: "Guider 3 Ultra",
    group: "Flashforge",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: false,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },

  // AnkerMake
  {
    id: generateDeterministicUuid("AnkerMake M5|AnkerMake"),
    vendorName: "AnkerMake",
    modelName: "M5",
    group: "AnkerMake",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("AnkerMake M5C|AnkerMake"),
    vendorName: "AnkerMake",
    modelName: "M5C",
    group: "AnkerMake",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },

  // Artillery
  {
    id: generateDeterministicUuid("Artillery Sidewinder X4 Plus|Artillery"),
    vendorName: "Artillery",
    modelName: "Sidewinder X4 Plus",
    group: "Artillery",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 220,
    buildPlateY: 220,
    active: true,
  },
  {
    id: generateDeterministicUuid("Artillery Sidewinder X4 Pro|Artillery"),
    vendorName: "Artillery",
    modelName: "Sidewinder X4 Pro",
    group: "Artillery",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 220,
    buildPlateY: 220,
    active: true,
  },
  {
    id: generateDeterministicUuid("Artillery Genius Pro|Artillery"),
    vendorName: "Artillery",
    modelName: "Genius Pro",
    group: "Artillery",
    maxBedTempC: 100,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 200,
    buildPlateY: 200,
    active: true,
  },
  {
    id: generateDeterministicUuid("Artillery Hornet|Artillery"),
    vendorName: "Artillery",
    modelName: "Hornet",
    group: "Artillery",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 200,
    buildPlateY: 200,
    active: true,
  },

  // Sovol
  {
    id: generateDeterministicUuid("Sovol SV06|Sovol"),
    vendorName: "Sovol",
    modelName: "SV06",
    group: "Sovol",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 235,
    buildPlateY: 235,
    active: true,
  },
  {
    id: generateDeterministicUuid("Sovol SV06 Plus|Sovol"),
    vendorName: "Sovol",
    modelName: "SV06 Plus",
    group: "Sovol",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },
  {
    id: generateDeterministicUuid("Sovol SV07 Plus|Sovol"),
    vendorName: "Sovol",
    modelName: "SV07 Plus",
    group: "Sovol",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },
  {
    id: generateDeterministicUuid("Sovol SV08|Sovol"),
    vendorName: "Sovol",
    modelName: "SV08",
    group: "Sovol",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },
  {
    id: generateDeterministicUuid("Sovol SV09|Sovol"),
    vendorName: "Sovol",
    modelName: "SV09",
    group: "Sovol",
    maxBedTempC: 110,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },

  // QIDI Tech
  {
    id: generateDeterministicUuid("QIDI Tech X-Plus 4|QIDI Tech"),
    vendorName: "QIDI Tech",
    modelName: "X-Plus 4",
    group: "QIDI Tech",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: false,
    buildPlateX: 300,
    buildPlateY: 250,
    active: true,
  },
  {
    id: generateDeterministicUuid("QIDI Tech X-Max 4|QIDI Tech"),
    vendorName: "QIDI Tech",
    modelName: "X-Max 4",
    group: "QIDI Tech",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: false,
    buildPlateX: 400,
    buildPlateY: 400,
    active: true,
  },
  {
    id: generateDeterministicUuid("QIDI Tech X-CF Pro|QIDI Tech"),
    vendorName: "QIDI Tech",
    modelName: "X-CF Pro",
    group: "QIDI Tech",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: false,
    buildPlateX: 300,
    buildPlateY: 250,
    active: true,
  },
  {
    id: generateDeterministicUuid("QIDI Tech Q1 Pro|QIDI Tech"),
    vendorName: "QIDI Tech",
    modelName: "Q1 Pro",
    group: "QIDI Tech",
    maxBedTempC: 100,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 255,
    buildPlateY: 255,
    active: true,
  },

  // Voron
  {
    id: generateDeterministicUuid("Voron 0.2|Voron"),
    vendorName: "Voron",
    modelName: "0.2",
    group: "Voron",
    maxBedTempC: 100,
    maxNozzleTempC: 280,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 120,
    buildPlateY: 120,
    active: true,
  },
  {
    id: generateDeterministicUuid("Voron Trident|Voron"),
    vendorName: "Voron",
    modelName: "Trident",
    group: "Voron",
    maxBedTempC: 110,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },
  {
    id: generateDeterministicUuid("Voron 2.4|Voron"),
    vendorName: "Voron",
    modelName: "2.4",
    group: "Voron",
    maxBedTempC: 110,
    maxNozzleTempC: 300,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 350,
    buildPlateY: 350,
    active: true,
  },
  {
    id: generateDeterministicUuid("Voron Switchwire|Voron"),
    vendorName: "Voron",
    modelName: "Switchwire",
    group: "Voron",
    maxBedTempC: 100,
    maxNozzleTempC: 280,
    isEnclosed: false,
    isDirectDrive: true,
    buildPlateX: 250,
    buildPlateY: 250,
    active: true,
  },

  // Bambu Lab (Budget)
  {
    id: generateDeterministicUuid("Bambu Lab A2 Mini|Bambu Lab"),
    vendorName: "Bambu Lab",
    modelName: "A2 Mini",
    group: "Bambu Lab (Budget)",
    maxBedTempC: 65,
    maxNozzleTempC: 260,
    isEnclosed: true,
    isDirectDrive: true,
    buildPlateX: 256,
    buildPlateY: 256,
    active: true,
  },

  // Other / Custom Printer
  {
    id: generateDeterministicUuid("Other / Custom Printer|Other / DIY"),
    vendorName: "Custom",
    modelName: "Other / Custom Printer",
    group: "Other / DIY",
    maxBedTempC: 100,
    maxNozzleTempC: 240,
    isEnclosed: false,
    isDirectDrive: false,
    active: true,
    notes: "Placeholder for user-defined custom printers",
  },
];

// ─── Default Bed Surfaces ──────────────────────────────────────────────────────

export const DEFAULT_SURFACES: EquipmentSurface[] = [
  // PEI (most common)
  {
    id: generateDeterministicUuid("PEI Textured|PEI (most common)"),
    displayName: "PEI Textured",
    internalKey: "PEI Textured",
    group: "PEI (most common)",
    maxTempC: 80,
    description: "Spring steel w/ texture — ships with most modern printers",
    active: true,
  },
  {
    id: generateDeterministicUuid("PEI Smooth|PEI (most common)"),
    displayName: "PEI Smooth",
    internalKey: "PEI Smooth",
    group: "PEI (most common)",
    maxTempC: 80,
    description: "Smooth PEI — great adhesion, mirror-flat bottom",
    active: true,
  },
  {
    id: generateDeterministicUuid("PEI Satin|PEI (most common)"),
    displayName: "PEI Satin",
    internalKey: "PEI Satin",
    group: "PEI (most common)",
    maxTempC: 80,
    description: "Matte finish, easier PETG/ABS release than smooth",
    active: true,
  },

  // Bambu Lab plates
  {
    id: generateDeterministicUuid("Bambu Cool Plate|Bambu Lab plates"),
    displayName: "Bambu Cool Plate",
    internalKey: "CoolPlate",
    group: "Bambu Lab plates",
    maxTempC: 65,
    description: "PEO-coated — PLA only, peel off when cool",
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Engineering Plate|Bambu Lab plates"),
    displayName: "Bambu Engineering Plate",
    internalKey: "EngineeringPlate",
    group: "Bambu Lab plates",
    maxTempC: 80,
    description: "For ABS/ASA/PC/PA — needs glue stick for PLA",
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu High-Temp Plate|Bambu Lab plates"),
    displayName: "Bambu High-Temp Plate",
    internalKey: "HighTempPlate",
    group: "Bambu Lab plates",
    maxTempC: 120,
    description: "PA, PC, PEI filament — rated 120°C+",
    active: true,
  },
  {
    id: generateDeterministicUuid("Bambu Dual-Sided Plate|Bambu Lab plates"),
    displayName: "Bambu Dual-Sided Plate",
    internalKey: "DualSidedPlate",
    group: "Bambu Lab plates",
    maxTempC: 80,
    description: "Textured PEI one side, smooth PEI other",
    active: true,
  },

  // Specialty surfaces
  {
    id: generateDeterministicUuid("Wham Bam|Specialty surfaces"),
    displayName: "Wham Bam PEX",
    internalKey: "WhamBam",
    group: "Specialty surfaces",
    maxTempC: 100,
    description: "Flexible magnetic system — good all-around adhesion",
    active: true,
  },
  {
    id: generateDeterministicUuid("Garolite|Specialty surfaces"),
    displayName: "Garolite (G10)",
    internalKey: "Garolite",
    group: "Specialty surfaces",
    maxTempC: 100,
    description: "Excellent for Nylon/PA — mediocre for PLA",
    active: true,
  },
  {
    id: generateDeterministicUuid("BuildTak|Specialty surfaces"),
    displayName: "BuildTak",
    internalKey: "BuildTak",
    group: "Specialty surfaces",
    maxTempC: 100,
    description: "Adhesive surface — good for ABS, difficult to remove",
    active: true,
  },
  {
    id: generateDeterministicUuid("SuperTack|Specialty surfaces"),
    displayName: "SuperTack Cool Plate",
    internalKey: "SuperTack",
    group: "Specialty surfaces",
    maxTempC: 100,
    description: "Self-releasing at room temp — no adhesives needed",
    active: true,
  },
  {
    id: generateDeterministicUuid("Magnetic Flex|Specialty surfaces"),
    displayName: "Magnetic Flex (generic)",
    internalKey: "MagFlex",
    group: "Specialty surfaces",
    maxTempC: 100,
    description: "Generic magnetic spring steel plate",
    active: true,
  },

  // Glass
  {
    id: generateDeterministicUuid("Glass|Glass"),
    displayName: "Borosilicate Glass",
    internalKey: "Glass",
    group: "Glass",
    maxTempC: 110,
    description: "Flat, needs glue stick or hairspray for most filaments",
    active: true,
  },
  {
    id: generateDeterministicUuid("Carborundum|Glass"),
    displayName: "Carborundum Glass",
    internalKey: "Carborundum",
    group: "Glass",
    maxTempC: 110,
    description: "Micro-textured glass — good PLA adhesion without glue",
    active: true,
  },

  // Other
  {
    id: generateDeterministicUuid("Other|Other"),
    displayName: "Other / Unknown",
    internalKey: "Other",
    group: "Other",
    maxTempC: 100,
    description: "Use generic defaults",
    active: true,
  },
];

// ─── Default Nozzles ───────────────────────────────────────────────────────────

export const DEFAULT_NOZZLES: EquipmentNozzle[] = [
  // Brass 0.4mm (standard)
  {
    id: generateDeterministicUuid("brass-0.4-standard"),
    diameterMm: 0.4,
    material: "brass",
    type: "standard",
    active: true,
  },
  // Hardened Steel
  {
    id: generateDeterministicUuid("hardened_steel-0.4-standard"),
    diameterMm: 0.4,
    material: "hardened_steel",
    type: "standard",
    active: true,
  },
  // Stainless Steel
  {
    id: generateDeterministicUuid("stainless_steel-0.4-standard"),
    diameterMm: 0.4,
    material: "stainless_steel",
    type: "standard",
    active: true,
  },
  // Ruby-Tipped
  {
    id: generateDeterministicUuid("ruby_tipped-0.4-standard"),
    diameterMm: 0.4,
    material: "ruby_tipped",
    type: "standard",
    active: true,
  },
  // Tungsten Carbide
  {
    id: generateDeterministicUuid("tungsten_carbide-0.4-standard"),
    diameterMm: 0.4,
    material: "tungsten_carbide",
    type: "standard",
    active: true,
  },
  // Copper-Plated
  {
    id: generateDeterministicUuid("copper_plated-0.4-standard"),
    diameterMm: 0.4,
    material: "copper_plated",
    type: "standard",
    active: true,
  },
  // Various diameters for standard material
  {
    id: generateDeterministicUuid("brass-0.2-standard"),
    diameterMm: 0.2,
    material: "brass",
    type: "standard",
    active: true,
  },
  {
    id: generateDeterministicUuid("brass-0.6-standard"),
    diameterMm: 0.6,
    material: "brass",
    type: "standard",
    active: true,
  },
  {
    id: generateDeterministicUuid("brass-0.8-standard"),
    diameterMm: 0.8,
    material: "brass",
    type: "standard",
    active: true,
  },
  // High-flow types
  {
    id: generateDeterministicUuid("brass-0.4-cht"),
    diameterMm: 0.4,
    material: "brass",
    type: "cht",
    active: true,
  },
  {
    id: generateDeterministicUuid("brass-0.4-volcano"),
    diameterMm: 0.4,
    material: "brass",
    type: "volcano",
    active: true,
  },
  {
    id: generateDeterministicUuid("brass-0.4-induction"),
    diameterMm: 0.4,
    material: "brass",
    type: "induction",
    active: true,
  },
];
