import { z } from "zod";
import type { LoadDirection, OrientationAssessment, OrientationRecommendation } from "./types";

/**
 * ─── Orientation Recommendation Schemas ──────────────────────────────────────
 *
 * Zod validation for load direction inputs and AI-generated orientation recommendations.
 * Used in form validation and API response validation.
 */

/**
 * Load direction options for functional/structural prints.
 * Maps to LoadDirection type for type safety.
 */
export const LoadDirectionSchema = z.enum([
  "vertical_tension",
  "vertical_compression",
  "cantilever",
  "torsional",
  "multi_directional",
  "impact",
  "fatigue",
]) as z.ZodType<LoadDirection>;

/**
 * Assessment of current part orientation relative to load.
 * Maps to OrientationAssessment type.
 */
export const OrientationAssessmentSchema = z.enum([
  "excellent",
  "good",
  "suboptimal",
  "poor",
]) as z.ZodType<OrientationAssessment>;

/**
 * Complete orientation recommendation object generated by Claude.
 * All fields are required and have length constraints for UI consistency.
 */
export const OrientationRecommendationSchema = z.object({
  principle: z
    .string()
    .min(20, "Principle must explain FDM anisotropy concept")
    .max(500, "Principle explanation too long"),

  recommendation: z
    .string()
    .min(15, "Recommendation must be specific")
    .max(300, "Recommendation too long"),

  strengthImprovement: z
    .string()
    .min(10, "Strength improvement estimate required")
    .max(150, "Strength improvement text too long"),

  currentOrientationAssessment: OrientationAssessmentSchema,

  currentOrientationReason: z
    .string()
    .min(15, "Must explain current orientation assessment")
    .max(400, "Explanation too long"),

  slicerInstructions: z
    .string()
    .min(20, "Slicer instructions must be specific")
    .max(500, "Instructions too long"),

  additionalConsiderations: z
    .string()
    .min(10, "Material considerations required")
    .max(400, "Considerations text too long"),

  warningIfIgnored: z
    .string()
    .min(15, "Warning message required")
    .max(300, "Warning too long"),
}) as z.ZodType<OrientationRecommendation>;

/**
 * User input form validation for load direction fields.
 * Both fields are optional; present only when functional/structural print.
 */
export const LoadDirectionInputSchema = z.object({
  loadDirection: LoadDirectionSchema.optional(),
  loadDescription: z
    .string()
    .max(75, "Load description limited to 75 characters")
    .optional(),
});

/**
 * Partial schema for API requests that include load direction.
 * Used to validate recommendation endpoint input.
 */
export const RecommendationRequestLoadSchema = z.object({
  loadDirection: LoadDirectionSchema.optional(),
  loadDescription: z
    .string()
    .max(75, "Load description limited to 75 characters")
    .optional(),
});
