export interface ReleaseNote {
  version: string;
  date: string; // ISO 8601
  changes: string[];
}

const RELEASE_NOTES: ReleaseNote[] = [
  {
    version: "1.2.0",
    date: "2026-04-12T23:59:00Z",
    changes: [
      "Branded share card: every results page and saved session view now shows a live canvas preview (600×315 display, 1200×630 actual) of a shareable PNG card — dark background, tier badge, settings grid, filament and printer info",
      "Download PNG button exports the card directly to file (on iOS Safari: opens in new tab for long-press save)",
      "Copy share text button copies a plain-text settings summary to clipboard — works in all browsers via Clipboard API with execCommand fallback",
      "Share card updates live: changing the session name or outcome flag re-renders the canvas preview within 300ms (debounced)",
      "Outcome flag: three-state print result picker — ✓ Success, ~ Partial, ✗ Failed — shown on the results page after every analysis and on each saved session view",
      "Outcome flag pill appears in the card header on the history page for at-a-glance scanning",
      "Compact OutcomeFlagSelector on each history card lets you flag previous sessions without opening the full view",
      "Outcome flag is included in the branded share card and share text when set",
      "Results page outcome section starts at 65% opacity until first interaction — non-intrusive until the user is ready to log the result",
      "Outcome summary row on the history page: 'Your prints: ✓ N successful, ~ N partial, ✗ N failed' — shown when ≥2 sessions have been flagged",
      "Share card download button on each history card lets you generate a PNG for any past session without reopening it",
      "Session ID written to sessionStorage (printperfect_current_session_id) at save time for future cross-tab coordination",
      "OutcomeFlag persisted to localStorage via updateSessionOutcomeFlag — merges with existing stars and notes, backward-compatible with pre-v1.2 sessions",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-04-12T23:30:00Z",
    changes: [
      "Print session history: every successful analysis is automatically saved to localStorage (up to 5 sessions, newest first) — no user action required",
      "Auto-generated session name based on filename + quality tier; editable inline on the results page and history page, debounced 500ms saves",
      "'Session saved to your print history' toast notification appears at the bottom of the results page after each save and fades after 3 seconds",
      "History nav link with live session count badge in the site header — updates immediately when sessions are added or deleted",
      "/history page: vertical list of session cards showing printer, filament, quality tier, key settings summary, estimated filament weight/length",
      "Inline star rating (1–5) on each history card and on the full saved session view — clicking the same star clears the rating",
      "Outcome notes: 50-word max textarea on each session, saves on blur, shows truncated text with expand on hover",
      "Side-by-side comparison: select two sessions via 'Compare' toggle buttons, sticky bar shows selection state, navigates to /history/compare?a=id&b=id",
      "Comparison page highlights differing values in amber with a ≠ indicator; identical values displayed in muted text",
      "'Key differences at a glance' summary section at the bottom of the compare page — pure JS, no AI call",
      "/history/[id] read-only session view: shows the saved banner, full results panels with stored AI explanations, and a rate/note section below",
      "Delete sessions from the history page with a two-click confirmation pattern (first click shows confirm/cancel inline)",
      "Private browsing graceful fallback: shows a notice when localStorage is unavailable; no errors thrown",
      "Server-side rate limit 429 responses now surface the same tip-to-unlock modal as the client-side UX limit",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-04-12T22:00:00Z",
    changes: [
      "Token economics: 3 free analyses per day, tracked in localStorage — counter resets automatically at local midnight",
      "Usage counter shown between the progress indicator and the form (hidden until after the user's first run to avoid front-loading anxiety)",
      "Counter turns amber when 1 analysis remains; shows 'Unlocked' in teal when unlimited; shows 'Daily limit reached · Unlock →' link when exhausted",
      "Limit modal: warm, non-guilt-tripping overlay shown when a 4th analysis is attempted — primary CTA links to Ko-fi tip page",
      "Honour-system unlock: user enters any 4–12 character alphanumeric code after tipping; no server verification — trust is the point",
      "Re-used code detection: if the same code is entered twice in one day, it is rejected with a clear message",
      "Auto-continue: after entering a valid code, the modal shows a thank-you message and automatically resumes the blocked analysis after 2 seconds",
      "Server-side rate limiting: in-memory Map tracks up to 10 requests per IP per day as an abuse backstop — resets on server restart, deliberately above the UX limit to accommodate shared IPs",
      "429 responses from the server surface the same limit modal to the user rather than a generic error",
      "Confirmed: ANTHROPIC_API_KEY is server-side only (in /api/recommend/route.ts); never exposed to client-side code",
      "Private/incognito graceful fallback: localStorage unavailability treated as a fresh session with full 3 analyses — no errors thrown",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-04-11T10:00:00Z",
    changes: [
      "Initial project scaffold — Next.js 14, TypeScript, Tailwind CSS",
      "Client-side STL, OBJ, and 3MF file parsing with geometry analysis",
      "Rule-based settings engine (layer height, temps, speed, infill, supports, adhesion)",
      "Claude AI integration for plain-English setting explanations",
      "Three-step flow: Upload → Configure → Results",
      "Progress indicator, mobile-friendly layout, Ko-fi tip jar embed",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-04-11T12:00:00Z",
    changes: [
      "Three.js real-time 3D model viewer with orbit controls and auto-rotate",
      "Dark mode / light mode pill toggle with system-preference detection",
      "Expanded printer list to 55+ models in grouped optgroups (Bambu, Creality, Prusa, Elegoo, Voron, etc.)",
      "Added PLA+, PLA-CF, PETG-CF, Nylon, and Polycarbonate filament types with correct temperature profiles",
      "Complexity rating now explains itself (e.g. 'flat/low-profile — lies cleanly on the bed')",
      "Fixed overhang detection: bed-zone faces no longer counted as overhangs",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-04-11T14:00:00Z",
    changes: [
      "3MF multi-file (Bambu Studio / PrusaSlicer) format support — follows component p:path references",
      "Switched from DOM XML parsing to regex-based parsing, eliminating all XML namespace issues",
      "Confidence score badges per setting (High / Medium / Low) generated by Claude",
      "New 'Common Mistakes to Avoid' section on results page, tailored to filament and printer",
      "PDF download via print-optimised stylesheet and browser Save as PDF",
      "SVG filament spool icon replaces printer emoji in header",
      "Header logo now resets the entire app to step 1 on click",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-04-11T16:00:00Z",
    changes: [
      "Password-protected admin panel at /admin with session cookie auth",
      "Admin: live Claude model selector (Haiku / Sonnet / Opus) — applies server-wide instantly",
      "Admin: release notes changelog with version history",
      "Dark mode contrast fixes — all headings and body text now meet WCAG AA on dark backgrounds",
      "Expanded printer list: Bambu H2D, P2S, A1 Combo, X1E; Creality Ender 3 V3 KE, K2 Plus; Prusa Core One; and more",
      "Expanded bed surface types: Bambu Cool Plate, High-Temp Plate, Engineering Plate, Wham Bam, Garolite, PEI Smooth, Textured PEI, Satin PEI — with per-surface temperature adjustments",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-04-12T14:00:00Z",
    changes: [
      "Replaced 3-tier Speed/Quality/Strength system with 4 calibrated quality tiers: Draft (0.28mm), Standard (0.20mm), Quality (0.12mm), Ultra (0.08mm)",
      "Standard is now the default selection — the balanced everyday starting point",
      "Strength is no longer a quality tier; selecting 'Functional part' adds +10% infill and +1 wall on top of any tier",
      "Recalibrated print time formula: Standard now estimates ~2–3h for a typical 50mm cube (was over-estimated)",
      "Ultra tier shows an advisory warning: not recommended for large models due to extreme print times",
      "Added PLA Silk as a distinct filament type with correct settings: 230°C nozzle, 65°C bed, ≤35mm/s, 90% cooling",
      "PLA Silk triggers three specific beginner warnings in Claude's AI explanation (stringing, speed, finish tips)",
      "Open Filament Database queries for PLA Silk use the 'silk' material filter for accurate brand data",
      "Filament weight/length estimate in the stats grid now updates live as quality tier or functional toggle changes",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-04-12T20:00:00Z",
    changes: [
      "Pre-upload tips panel: collapsible 'Tips for best results' panel on the upload screen with 5 beginner-friendly tips covering STL vs 3MF, mesh quality, one-part workflow, and file size — collapse state persisted in localStorage",
      "Multi-object .3mf detection: lightweight XML inspection before geometry analysis detects files with multiple objects or build items",
      "Multi-object warning flow: if a .3mf contains multiple objects, users see an in-page warning with options to proceed anyway or upload a different file",
      "If the user proceeds past the warning, a persistent amber banner appears on the results page noting that accuracy may be reduced",
      "Filament showcase card: replaces the small provenance badge with a prominent card at the top of the results page showing brand, material, finish, color, temp ranges, diameter, density, and a left border accent color-coded by material type",
      "Claude now generates a 'materialBlurb' — 2–3 plain-English sentences about the filament material type — shown in the showcase card's 'About this material' section",
      "Open Filament Database extended fields (diameter, density, color, finish) now extracted and shown when returned by the API",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-04-12T18:00:00Z",
    changes: [
      "Advanced settings panels: each results category (Temperature, Speed, Cooling, Supports, Adhesion) now has a collapsible 'Advanced settings' section with beginner-friendly explanations",
      "Advanced values are fully computed from the rule engine — adjusted per filament type, quality tier, and model geometry, not hardcoded",
      "Smooth expand/collapse animation with keyboard accessibility (Enter/Space to toggle each panel)",
      "Developer debug panel removed from the public results page — no trace remains",
      "New admin debug route at /admin/debug: passphrase-protected, shows geometry JSON, full Claude prompt, raw API response, filament DB result, and computed settings",
      "Debug data saved to localStorage after each analysis run so /admin/debug always shows the most recent session",
      "'Copy full debug report' button on debug page copies everything as formatted JSON to clipboard",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-04-12T10:00:00Z",
    changes: [
      "Auto-orient: mesh is automatically rotated so the largest flat face rests on the build plate before any analysis runs",
      "Overhang detection, support recommendations, and bounding box now reflect the corrected printing orientation",
      "Info note shown below the 3D viewer when auto-orientation was applied ('Model auto-oriented to optimal build plate position')",
      "Volume stat replaced with estimated filament weight (grams) and length (meters) — beginner-friendly numbers",
      "Filament estimates use per-material density values and account for shell walls (100% density) vs infilled interior",
      "Form view shows weight/length at 20% infill default; results view uses the actual computed infill percentage",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-04-11T18:00:00Z",
    changes: [
      "Live Weather Widget — geolocation + Open-Meteo API auto-fills room humidity level",
      "Open Filament Database integration — real manufacturer temp data shown as a badge when brand is entered",
      "Multi-printer Profile Manager — save up to 10 printer setups in localStorage, load them with one click",
      "Quick-save '💾 Save setup' button on form submits current printer/nozzle/surface as a named profile",
      "Profiles survive browser restarts; graceful fallback in private/incognito mode",
      "Admin gear icon (⚙) always visible in header for quick access to settings panel",
    ],
  },
];

export default RELEASE_NOTES;
